version: 2.1

jobs:
  eslint:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run ESLint
          command: npx eslint .

workflows:
  main-workflow:
    jobs:
      - eslint
